apply plugin: 'com.android.application'

android {
    compileSdk 35
    defaultConfig {
        applicationId 'net.hyx.app.volumenotification'
        minSdkVersion 21
        targetSdk 35
        versionCode 13500
        versionName '1.3.5'
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true
            pseudoLocalesEnabled = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled = true
            shrinkResources = true
            pseudoLocalesEnabled = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
    namespace = 'net.hyx.app.volumenotification'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.fragment:fragment:1.8.9'
    implementation 'androidx.work:work-runtime:2.10.5'
    implementation 'com.google.code.gson:gson:2.14.0'
    implementation 'com.google.android.material:material:1.13.0'
    androidTestImplementation 'junit:junit:4.13.2'
}
